### ISSUE TITLE
Support grouping tasks

### ISSUE THREAD

**Issue by michael-etzkorn** [hilotter/github-gantt-chart#220]
Hi, I think this app is really neat. It's the kind of gantt chart integration I was looking for. 

It'd be cool if there could be a way to group issues by an ID instead of just sequentially ordering them. I'm essentially trying to convert some milestones to a gantt chart, but the meta issues tracking the milestones weren't created sequentially.

Something like 
```
#### 🗓 Start Date: 2020-04-01 <= YYYY-MM-DD format (required)
#### 🗓 End Date: 2020-04-10 <= YYYY-MM-DD format (required)
#### 📈 Progress (0-1): 0.2 <= (optional)
#### 📝 Dependencies: #1, #2 <= related issues separated by , (optional)
#### 🧮 id: v
```
And that groups all tasks with id v. The actual order of the id's feels less important to me. 

![image](https://user-images.githubusercontent.com/88842659/175432536-7bc6a572-29ed-4a94-ade7-659ae5c5a931.png)

**Comment by hilotter** [comment]
@michael-etzkorn  Hi,  sorry for late repling.

I think your idea is very good.
So grouping tasks now supported by #222
Grouping tasks can be used by adding the following format.

```
#### 🧮 Group: group_name
```

Thank you for your suggestion.
